name: Publish Docker Image (Multiplatform)

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        run: docker buildx create --use
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --file ./Dockerfile \
            --build-arg USER=${{ github.actor }} \
            --build-arg TOKEN=${{ secrets.GITHUB_TOKEN }} \
            --platform linux/arm64,linux/amd64 \
            --tag ${{env.REGISTRY}}/${{github.repository}} \
            --push .
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     build-args: |
      #       USER=${{ github.actor }}
      #       TOKEN=${{ secrets.GITHUB_TOKEN }}
      #     push: true
      #     tags: ${{env.REGISTRY}}/${{github.repository}}
